/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCostRouteImport } from './routes/api-cost'
import { Route as PromoRouteImport } from './routes/promo'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as ResolverRouteImport } from './routes/resolver'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as WorkersRouteImport } from './routes/workers'
import { Route as ApiActivateNativeApifyRouteImport } from './routes/api/activate-native-apify'
import { Route as ApiAutopilotRouteImport } from './routes/api/autopilot'
import { Route as ApiPromoCommitRouteImport } from './routes/api/promo-commit'
import { Route as ApiPromoQueueRouteImport } from './routes/api/promo-queue'
import { Route as ApiPromoStatusRouteImport } from './routes/api/promo-status'
import { Route as ApiSourceEngineActionRouteImport } from './routes/api/source-engine/$action'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCostRoute = ApiCostRouteImport.update({
  id: '/api-cost',
  path: '/api-cost',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoRoute = PromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolverRoute = ResolverRouteImport.update({
  id: '/resolver',
  path: '/resolver',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersRoute = WorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActivateNativeApifyRoute = ApiActivateNativeApifyRouteImport.update({
  id: '/api/activate-native-apify',
  path: '/api/activate-native-apify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutopilotRoute = ApiAutopilotRouteImport.update({
  id: '/api/autopilot',
  path: '/api/autopilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoCommitRoute = ApiPromoCommitRouteImport.update({
  id: '/api/promo-commit',
  path: '/api/promo-commit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoQueueRoute = ApiPromoQueueRouteImport.update({
  id: '/api/promo-queue',
  path: '/api/promo-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoStatusRoute = ApiPromoStatusRouteImport.update({
  id: '/api/promo-status',
  path: '/api/promo-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceEngineActionRoute = ApiSourceEngineActionRouteImport.update({
  id: '/api/source-engine/$action',
  path: '/api/source-engine/$action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-cost': typeof ApiCostRoute
  '/promo': typeof PromoRoute
  '/queue': typeof QueueRoute
  '/radar': typeof RadarRoute
  '/resolver': typeof ResolverRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workers': typeof WorkersRoute
  '/api/activate-native-apify': typeof ApiActivateNativeApifyRoute
  '/api/autopilot': typeof ApiAutopilotRoute
  '/api/promo-commit': typeof ApiPromoCommitRoute
  '/api/promo-queue': typeof ApiPromoQueueRoute
  '/api/promo-status': typeof ApiPromoStatusRoute
  '/api/source-engine/$action': typeof ApiSourceEngineActionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-cost': typeof ApiCostRoute
  '/promo': typeof PromoRoute
  '/queue': typeof QueueRoute
  '/radar': typeof RadarRoute
  '/resolver': typeof ResolverRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workers': typeof WorkersRoute
  '/api/activate-native-apify': typeof ApiActivateNativeApifyRoute
  '/api/autopilot': typeof ApiAutopilotRoute
  '/api/promo-commit': typeof ApiPromoCommitRoute
  '/api/promo-queue': typeof ApiPromoQueueRoute
  '/api/promo-status': typeof ApiPromoStatusRoute
  '/api/source-engine/$action': typeof ApiSourceEngineActionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-cost': typeof ApiCostRoute
  '/promo': typeof PromoRoute
  '/queue': typeof QueueRoute
  '/radar': typeof RadarRoute
  '/resolver': typeof ResolverRoute
  '/settings': typeof SettingsRoute
  '/sources': typeof SourcesRoute
  '/workers': typeof WorkersRoute
  '/api/activate-native-apify': typeof ApiActivateNativeApifyRoute
  '/api/autopilot': typeof ApiAutopilotRoute
  '/api/promo-commit': typeof ApiPromoCommitRoute
  '/api/promo-queue': typeof ApiPromoQueueRoute
  '/api/promo-status': typeof ApiPromoStatusRoute
  '/api/source-engine/$action': typeof ApiSourceEngineActionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-cost'
    | '/promo'
    | '/queue'
    | '/radar'
    | '/resolver'
    | '/settings'
    | '/sources'
    | '/workers'
    | '/api/activate-native-apify'
    | '/api/autopilot'
    | '/api/promo-commit'
    | '/api/promo-queue'
    | '/api/promo-status'
    | '/api/source-engine/$action'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-cost'
    | '/promo'
    | '/queue'
    | '/radar'
    | '/resolver'
    | '/settings'
    | '/sources'
    | '/workers'
    | '/api/activate-native-apify'
    | '/api/autopilot'
    | '/api/promo-commit'
    | '/api/promo-queue'
    | '/api/promo-status'
    | '/api/source-engine/$action'
  id:
    | '__root__'
    | '/'
    | '/api-cost'
    | '/promo'
    | '/queue'
    | '/radar'
    | '/resolver'
    | '/settings'
    | '/sources'
    | '/workers'
    | '/api/activate-native-apify'
    | '/api/autopilot'
    | '/api/promo-commit'
    | '/api/promo-queue'
    | '/api/promo-status'
    | '/api/source-engine/$action'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCostRoute: typeof ApiCostRoute
  PromoRoute: typeof PromoRoute
  QueueRoute: typeof QueueRoute
  RadarRoute: typeof RadarRoute
  ResolverRoute: typeof ResolverRoute
  SettingsRoute: typeof SettingsRoute
  SourcesRoute: typeof SourcesRoute
  WorkersRoute: typeof WorkersRoute
  ApiActivateNativeApifyRoute: typeof ApiActivateNativeApifyRoute
  ApiAutopilotRoute: typeof ApiAutopilotRoute
  ApiPromoCommitRoute: typeof ApiPromoCommitRoute
  ApiPromoQueueRoute: typeof ApiPromoQueueRoute
  ApiPromoStatusRoute: typeof ApiPromoStatusRoute
  ApiSourceEngineActionRoute: typeof ApiSourceEngineActionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-cost': {
      id: '/api-cost'
      path: '/api-cost'
      fullPath: '/api-cost'
      preLoaderRoute: typeof ApiCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo': {
      id: '/promo'
      path: '/promo'
      fullPath: '/promo'
      preLoaderRoute: typeof PromoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resolver': {
      id: '/resolver'
      path: '/resolver'
      fullPath: '/resolver'
      preLoaderRoute: typeof ResolverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers': {
      id: '/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof WorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/activate-native-apify': {
      id: '/api/activate-native-apify'
      path: '/api/activate-native-apify'
      fullPath: '/api/activate-native-apify'
      preLoaderRoute: typeof ApiActivateNativeApifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autopilot': {
      id: '/api/autopilot'
      path: '/api/autopilot'
      fullPath: '/api/autopilot'
      preLoaderRoute: typeof ApiAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo-commit': {
      id: '/api/promo-commit'
      path: '/api/promo-commit'
      fullPath: '/api/promo-commit'
      preLoaderRoute: typeof ApiPromoCommitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo-queue': {
      id: '/api/promo-queue'
      path: '/api/promo-queue'
      fullPath: '/api/promo-queue'
      preLoaderRoute: typeof ApiPromoQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo-status': {
      id: '/api/promo-status'
      path: '/api/promo-status'
      fullPath: '/api/promo-status'
      preLoaderRoute: typeof ApiPromoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source-engine/$action': {
      id: '/api/source-engine/$action'
      path: '/api/source-engine/$action'
      fullPath: '/api/source-engine/$action'
      preLoaderRoute: typeof ApiSourceEngineActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCostRoute: ApiCostRoute,
  PromoRoute: PromoRoute,
  QueueRoute: QueueRoute,
  RadarRoute: RadarRoute,
  ResolverRoute: ResolverRoute,
  SettingsRoute: SettingsRoute,
  SourcesRoute: SourcesRoute,
  WorkersRoute: WorkersRoute,
  ApiActivateNativeApifyRoute: ApiActivateNativeApifyRoute,
  ApiAutopilotRoute: ApiAutopilotRoute,
  ApiPromoCommitRoute: ApiPromoCommitRoute,
  ApiPromoQueueRoute: ApiPromoQueueRoute,
  ApiPromoStatusRoute: ApiPromoStatusRoute,
  ApiSourceEngineActionRoute: ApiSourceEngineActionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
